# Generated by Django 2.2.6 on 2021-06-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room')},
        ),
    ]
